# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from edera_core.proto import edera_pb2 as edera__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in edera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EntityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/edera.v1.EntityService/Get',
                request_serializer=edera__pb2.EntityRef.SerializeToString,
                response_deserializer=edera__pb2.Entity.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/edera.v1.EntityService/List',
                request_serializer=edera__pb2.EntityQuery.SerializeToString,
                response_deserializer=edera__pb2.EntityList.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/edera.v1.EntityService/Query',
                request_serializer=edera__pb2.QueryRequest.SerializeToString,
                response_deserializer=edera__pb2.EntityList.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/edera.v1.EntityService/Create',
                request_serializer=edera__pb2.Entity.SerializeToString,
                response_deserializer=edera__pb2.Entity.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/edera.v1.EntityService/Update',
                request_serializer=edera__pb2.Entity.SerializeToString,
                response_deserializer=edera__pb2.Entity.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/edera.v1.EntityService/Delete',
                request_serializer=edera__pb2.EntityRef.SerializeToString,
                response_deserializer=edera__pb2.DeleteResult.FromString,
                _registered_method=True)


class EntityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EntityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=edera__pb2.EntityRef.FromString,
                    response_serializer=edera__pb2.Entity.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=edera__pb2.EntityQuery.FromString,
                    response_serializer=edera__pb2.EntityList.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=edera__pb2.QueryRequest.FromString,
                    response_serializer=edera__pb2.EntityList.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=edera__pb2.Entity.FromString,
                    response_serializer=edera__pb2.Entity.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=edera__pb2.Entity.FromString,
                    response_serializer=edera__pb2.Entity.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=edera__pb2.EntityRef.FromString,
                    response_serializer=edera__pb2.DeleteResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edera.v1.EntityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edera.v1.EntityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EntityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/Get',
            edera__pb2.EntityRef.SerializeToString,
            edera__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/List',
            edera__pb2.EntityQuery.SerializeToString,
            edera__pb2.EntityList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/Query',
            edera__pb2.QueryRequest.SerializeToString,
            edera__pb2.EntityList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/Create',
            edera__pb2.Entity.SerializeToString,
            edera__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/Update',
            edera__pb2.Entity.SerializeToString,
            edera__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.EntityService/Delete',
            edera__pb2.EntityRef.SerializeToString,
            edera__pb2.DeleteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Trigger = channel.unary_unary(
                '/edera.v1.DagService/Trigger',
                request_serializer=edera__pb2.DagTriggerRequest.SerializeToString,
                response_deserializer=edera__pb2.DagRunRef.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/edera.v1.DagService/Status',
                request_serializer=edera__pb2.DagRef.SerializeToString,
                response_deserializer=edera__pb2.DagStatus.FromString,
                _registered_method=True)
        self.Edit = channel.unary_unary(
                '/edera.v1.DagService/Edit',
                request_serializer=edera__pb2.DagEditRequest.SerializeToString,
                response_deserializer=edera__pb2.DagStatus.FromString,
                _registered_method=True)


class DagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Trigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Edit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Trigger': grpc.unary_unary_rpc_method_handler(
                    servicer.Trigger,
                    request_deserializer=edera__pb2.DagTriggerRequest.FromString,
                    response_serializer=edera__pb2.DagRunRef.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=edera__pb2.DagRef.FromString,
                    response_serializer=edera__pb2.DagStatus.SerializeToString,
            ),
            'Edit': grpc.unary_unary_rpc_method_handler(
                    servicer.Edit,
                    request_deserializer=edera__pb2.DagEditRequest.FromString,
                    response_serializer=edera__pb2.DagStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edera.v1.DagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edera.v1.DagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Trigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.DagService/Trigger',
            edera__pb2.DagTriggerRequest.SerializeToString,
            edera__pb2.DagRunRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.DagService/Status',
            edera__pb2.DagRef.SerializeToString,
            edera__pb2.DagStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Edit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.DagService/Edit',
            edera__pb2.DagEditRequest.SerializeToString,
            edera__pb2.DagStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Status = channel.unary_unary(
                '/edera.v1.NodeService/Status',
                request_serializer=edera__pb2.NodeRef.SerializeToString,
                response_deserializer=edera__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/edera.v1.NodeService/Stop',
                request_serializer=edera__pb2.NodeRef.SerializeToString,
                response_deserializer=edera__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.Resume = channel.unary_unary(
                '/edera.v1.NodeService/Resume',
                request_serializer=edera__pb2.NodeResumeRequest.SerializeToString,
                response_deserializer=edera__pb2.DagRunRef.FromString,
                _registered_method=True)
        self.Output = channel.unary_unary(
                '/edera.v1.NodeService/Output',
                request_serializer=edera__pb2.NodeOutputRequest.SerializeToString,
                response_deserializer=edera__pb2.NodeOutputList.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Resume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Output(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=edera__pb2.NodeRef.FromString,
                    response_serializer=edera__pb2.NodeStatus.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=edera__pb2.NodeRef.FromString,
                    response_serializer=edera__pb2.NodeStatus.SerializeToString,
            ),
            'Resume': grpc.unary_unary_rpc_method_handler(
                    servicer.Resume,
                    request_deserializer=edera__pb2.NodeResumeRequest.FromString,
                    response_serializer=edera__pb2.DagRunRef.SerializeToString,
            ),
            'Output': grpc.unary_unary_rpc_method_handler(
                    servicer.Output,
                    request_deserializer=edera__pb2.NodeOutputRequest.FromString,
                    response_serializer=edera__pb2.NodeOutputList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edera.v1.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edera.v1.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.NodeService/Status',
            edera__pb2.NodeRef.SerializeToString,
            edera__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.NodeService/Stop',
            edera__pb2.NodeRef.SerializeToString,
            edera__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Resume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.NodeService/Resume',
            edera__pb2.NodeResumeRequest.SerializeToString,
            edera__pb2.DagRunRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Output(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.NodeService/Output',
            edera__pb2.NodeOutputRequest.SerializeToString,
            edera__pb2.NodeOutputList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SystemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/edera.v1.SystemService/Health',
                request_serializer=edera__pb2.HealthRequest.SerializeToString,
                response_deserializer=edera__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Reload = channel.unary_unary(
                '/edera.v1.SystemService/Reload',
                request_serializer=edera__pb2.ReloadRequest.SerializeToString,
                response_deserializer=edera__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.InitClient = channel.unary_unary(
                '/edera.v1.SystemService/InitClient',
                request_serializer=edera__pb2.ClientInitRequest.SerializeToString,
                response_deserializer=edera__pb2.ClientInitResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/edera.v1.SystemService/SubscribeEvents',
                request_serializer=edera__pb2.EventSubscribeRequest.SerializeToString,
                response_deserializer=edera__pb2.EventMessage.FromString,
                _registered_method=True)


class SystemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=edera__pb2.HealthRequest.FromString,
                    response_serializer=edera__pb2.HealthResponse.SerializeToString,
            ),
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=edera__pb2.ReloadRequest.FromString,
                    response_serializer=edera__pb2.ReloadResponse.SerializeToString,
            ),
            'InitClient': grpc.unary_unary_rpc_method_handler(
                    servicer.InitClient,
                    request_deserializer=edera__pb2.ClientInitRequest.FromString,
                    response_serializer=edera__pb2.ClientInitResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=edera__pb2.EventSubscribeRequest.FromString,
                    response_serializer=edera__pb2.EventMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edera.v1.SystemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edera.v1.SystemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.SystemService/Health',
            edera__pb2.HealthRequest.SerializeToString,
            edera__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.SystemService/Reload',
            edera__pb2.ReloadRequest.SerializeToString,
            edera__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edera.v1.SystemService/InitClient',
            edera__pb2.ClientInitRequest.SerializeToString,
            edera__pb2.ClientInitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/edera.v1.SystemService/SubscribeEvents',
            edera__pb2.EventSubscribeRequest.SerializeToString,
            edera__pb2.EventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
