display_name: Trigger
business_id_field: name
display_template: "{name}"
storage_tier: filesystem
system_protected: true
schema:
  type: object
  required:
    - name
    - wait_for
    - target
  properties:
    name:
      type: string
    wait_for:
      type: string
    target:
      type: string
    enabled:
      type: boolean
      default: true
validate: true
