entities:
- id: stock-00700-hk
  type: stock
  attributes:
    code: 00700.HK
    name: Tencent
    holding:
      quantity: 100
      cost_price: 300
- id: stock-600519-sh
  type: stock
  attributes:
    code: 600519.SH
    name: Kweichow Moutai
- id: stock-hk0100
  type: stock
  attributes:
    code: 00100.HK
    name: Minimax
- id: stock-hk0020
  type: stock
  attributes:
    code: 00020.HK
    name: 商汤-W
