relations:
- id: 5bb16d7c48b540cda3195cfa4063be12
  entities:
  - stock:00100.HK
  - rss-source:hn-rss
  type: uses-source
  metadata: {}
- id: aae4b12ed23f49529279b4f504f19faf
  entities:
  - stock:00100.HK
  - api-source:cls-telegraph
  type: uses-source
  metadata: {}
- id: a78b6bc63d0b4e7ca48081ff715d4937
  entities:
  - stock:00100.HK
  - api-source:jqka
  type: uses-source
  metadata: {}
- id: 88a4475742dd4145a576e220f21efb4f
  entities:
  - stock:00100.HK
  - api-source:solidot
  type: uses-source
  metadata: {}
- id: cb630d3275884890a041eab926b0adeb
  entities:
  - stock:00100.HK
  - api-source:ithome
  type: uses-source
  metadata: {}
- id: 5581910c6a0049e9a8d0a21ae17be7a9
  entities:
  - stock:00100.HK
  - api-source:github
  type: uses-source
  metadata: {}
- id: 4b0a2d4629d44c939e2c79f5fa7c0020
  entities:
  - stock:00020.HK
  - rss-source:hn-rss
  type: uses-source
  metadata: {}
- id: 0ec64d14e7234c809c2e62e902c0020
  entities:
  - stock:00020.HK
  - api-source:cls-telegraph
  type: uses-source
  metadata: {}
- id: 04d94bd9c2844e37a5d4a240f8c0020
  entities:
  - stock:00020.HK
  - api-source:jqka
  type: uses-source
  metadata: {}
